### ISSUE TITLE
INoobotCore.GetUserIdForEmail

### ISSUE THREAD

**Issue by zimnyjakub** [noobot/noobot#102]
Hi,
for our project we need to gather slack UserID by email (our external systems match by email). As this is pretty simple, I have already implemented this on my fork - do you want me to create a pull request with this feature? This question also goes furhter - if I extend the project based on our requirements, do you want them pulled back (of course with prior discussion)?

**Comment by Workshop2** [comment]
Greetings @ddaron 

Please feel free to push changes back to Noobot, however, this is not required. Noobot has a MIT license so you can do what you want 👍
