### ISSUE TITLE
Bot does not respond back.

### ISSUE THREAD

**Issue by ocinbat** [noobot/noobot#118]
Hello,

I created a project from your examples and successfully connected to my workspace.
Whenever I type something in slack I can see a log stating "[Message found from 'omer.cinbat']" but I cannot get a response back from not even ping middle ware.

Could you point me somewhere I need to check?

**Comment by PHeonix25** [comment]
Hi @ocinbat - sorry for the delayed response.
Did you get this to work? Have you tried with the simplest of examples?

If so, could you please share your code and I can try and help you debug it.

**Comment by ocinbat** [comment]
I got it working mate. The problem was WelcomeMiddleware from tools. When I add it bot doesnt response back.
