### ISSUE TITLE
'FilterMessagesDirectedAtBot = false' does not seem to do anything

### ISSUE THREAD

**Issue by ghost** [noobot/noobot#12]
Setting `FilterMessagesDirectedAtBot = false` does not seem to allow the bot to filter messages.

**Comment by Workshop2** [comment]
So looks like it is working, but you need to use `message.Text` instead of `FormatTextTargettedAtBot()`. This is something I want to change...as that method isn't intuitive.

**Comment by Workshop2** [comment]
Fixed in #15
