### ISSUE TITLE
Unable To Connect - invalid_auth returned from Slack rtm.start API

### ISSUE THREAD

**Issue by AshleyPoole** [noobot/noobot#121]
Following the Wiki article for setting up the Bot as an Slack application (not the legacy integration) but it appears that maybe Slack have updated their UI/Permissions, so it no longer matches up with what is listed on the Wiki: https://github.com/noobot/noobot/wiki/Getting-Started-With-Noobot

Now when following the instructions in the Wiki and using the `Noobot.Console` example console application using the Bots (`xoxb-XXXXX`) user token, `invalid_auth` error is returned by the API, and an exception is thrown by the FlurlHandshakeClient class when its verifying the response -- due to the Slack API returning `invalid_auth`.

Do you know which combination of scopes are needed now @Workshop2 or @PHeonix25? Thanks!

**Comment by Workshop2** [comment]
Hey @AshleyPoole - yeah I recently got a slack API notification about deprecating APIs. I think the difficulty is that I'm not actively working with it near slack apps so I'm not sure when I can get to it. Is this something you'd be interested in doing?

https://api.slack.com/changelog/2021-10-rtm-start-to-stop#how

**Comment by AshleyPoole** [comment]
Done @Workshop2! PR raised against the SlackConnector project here: https://github.com/noobot/SlackConnector/pull/97

**Comment by Workshop2** [comment]
Thanks @AshleyPoole - I've pushed it to nuget. I'm not near a laptop for a few days so I did it on my phone. Fingers crossed it works for you 👍
