### ISSUE TITLE
Help functions that have no Handler e.g. ""

### ISSUE THREAD

**Issue by Workshop2** [noobot/noobot#19]
If a handle is empty (which is valid), then the help isn't very useful: this should be handled better :smile:

**Comment by Workshop2** [comment]
Maybe instead of matching on empty string it should match on a defined wild card?

**Comment by Workshop2** [comment]
E.g Handler.Defined.WildCard

**Comment by PHeonix25** [comment]
For now, I've opened #72 so that at least the output from `help` doesn't look broken.
