### ISSUE TITLE
What is the propose of 'StatsPlugin'

### ISSUE THREAD

**Issue by Caldas** [noobot/noobot#44]
Sorry create a ticket, but it's missing XMLDoc about the class and I didn't understood what is the propose of **StatsPlugin** class.

Can someone explain please?

**Comment by Workshop2** [comment]
Hey @Caldas,

This plugin is paired with the middleware "[StatsMiddleware](https://github.com/noobot/noobot/blob/master/src/Noobot.Domain/MessagingPipeline/Middleware/StandardMiddleware/StatsMiddleware.cs)" which will output interesting/debug information about the running bot. 

Generally it doesn't do anything super interesting, but can be insightful to see how long the bot has been running etc....

Hope this helps,
Simon

p.s. try running "@noobot stats"
