### ISSUE TITLE
Noobot doesn't works with StructureMap 4.4.0+

### ISSUE THREAD

**Issue by stawr93** [noobot/noobot#53]
Hello, guys.
I'm just got an error after updating StructureMap to the latest version.
There is following exception:
`Must be at least one IRegistrationConvention in the scanning operation
1.) Lambda: IContext.GetInstance().Start()
2.) Instance of Noobot.Examples.Web.INoobotHost
3.) new HomeController(*Default of INoobotHost*)
4.) Noobot.Examples.Web.Controllers.HomeController
5.) Instance of Noobot.Examples.Web.Controllers.HomeController
6.) Container.GetInstance(Noobot.Examples.Web.Controllers.HomeController)
   in lambda_method(Closure , IBuildSession , IContext )
   in StructureMap.Building.BuildPlan.Build(IBuildSession session, IContext context)
   in StructureMap.BuildSession.BuildNewInSession(Type pluginType, Instance instance)
   in StructureMap.BuildSession.BuildUnique(Type pluginType, Instance instance)
   in StructureMap.SessionCache.GetObject(Type pluginType, Instance instance, ILifecycle lifecycle)
   in StructureMap.SessionCache.GetDefault(Type pluginType, IPipelineGraph pipelineGraph)
   in StructureMap.Container.GetInstance(Type pluginType)
   in Noobot.Examples.Web.DependencyResolution.StructureMapDependencyScope.DoGetInstance(Type serviceType, String key) in C:\Users\Vitaly\Desktop\Noobot.Examples-master\src\Noobot.Examples.Web\DependencyResolution\StructureMapDependencyScope.cs:line 140
   in Microsoft.Practices.ServiceLocation.ServiceLocatorImplBase.GetInstance(Type serviceType, String key) in c:\Projects\CommonServiceLocator\main\Microsoft.Practices.ServiceLocation\ServiceLocatorImplBase.cs:line 49`

Steps to reproduce:
1. Use Noobot.Examples solution https://github.com/noobot/Noobot.Examples 
2. Update StructureMap via NuGet package manager
3. Start Noobot.Examples.Web

I think, this exception will be throwed on console example also.
Please, fix it ASAP 😄 I can't use StructureMap with version less than 4.4.0 because my project based on ASP.NET Core.

**Comment by Workshop2** [comment]
Thanks @stawr93 - I will take a look

**Comment by Workshop2** [comment]
Also @stawr93 - I doubt Noobot is dotnet core compatible as it has dependencies on other nuget packages.....just a heads up 😉

**Comment by Workshop2** [comment]
@stawr93 try this: https://www.nuget.org/packages/Noobot.Core/1.0.6157.16083

**Comment by stawr93** [comment]
Oh, so fast! Thank you, @Workshop2! I will try it.
About .NET Core... My project is targeting to full .net framework :) And in this case Noobot can be used (and it works fine). Of course, in case of targeting to netcoreapp Noobot isn't compatible.

**Comment by stawr93** [comment]
I've test it and 1.0.6157.16083 works fine. Thank you!
