### ISSUE TITLE
Build Fails

### ISSUE THREAD

**Issue by NicholasWelch** [noobot/noobot#55]
Downloading the latest release and using the build.ps1 fails with loads of errors.. such as:

NoobotCore.cs(240,33): error CS1003: Syntax error, ':' expected

**Comment by Workshop2** [comment]
Hi @NicholasWelch what version of visual studio are you using?

The build is currently passing so I am wondering if your using an older version...?

https://ci.appveyor.com/project/Workshop2/noobot

**Comment by Workshop2** [comment]
I am closing this issue due to lack of response
