### ISSUE TITLE
Do you plan to upgrade it to dotnetcore ?

### ISSUE THREAD

**Issue by jhayotte** [noobot/noobot#60]
Everything is in the title

**Comment by Workshop2** [comment]
Hello, 

There are some road blocks I would need to solve (such as finding a webwocket client that is compatible etc).

I don't have the time right now to look at it but the first thing to be done would be porting over the slack connector.

**Comment by kinetiq** [comment]
Just wanted to cast my vote for this. It's becoming increasingly important. :) 

There are some Core WebSockets clients now, such as: https://github.com/aspnet/WebSockets (not sure if it's suitable / right sized lego blocks)

**Comment by Workshop2** [comment]
Thanks @kinetiq 

Life is pretty busy right now but I do agree that this is something that is important. 

I will keep it in mind for the next big version 👍

**Comment by joelhulen** [comment]
+1 vote from me. If that websocket client @kinetiq linked to is sufficient, what other potential roadblocks are there? Have you run the (.NET Portability Analyzer)[https://marketplace.visualstudio.com/items?itemName=ConnieYau.NETPortabilityAnalyzer] on the project?

**Comment by Workshop2** [comment]
Hey everyone, I have started looking at a WebSocket replacement that has a DotNetCore library in the works - initial tests seem to prove it works.

**Comment by kinetiq** [comment]
Awesome. :) Once that's done, I should be able to containerize my bot. That will be killer.

**Comment by joelhulen** [comment]
Really looking forward to this, @Workshop2! The fact that your initial tests worked is very encouraging :)

**Comment by Workshop2** [comment]
@joelhulen - that was just testing a different websocket client that has .Net core compatibility. Will probably be doing little iterations towards core... Although I am happy to see more people interested in this feature :smile:

**Comment by Workshop2** [comment]
Currently refactoring out RestSharp to use Flurl due to lack of portability with .Net Core

**Comment by OmarBizreh** [comment]
Same here, waiting for DotNetCore support =)
Meanwhile using this version to learn more about Noobot ^_^

**Comment by joelhulen** [comment]
Hello, @Workshop2! Just wanted to see what your progress is on this? Were you successful in swapping out RestSharp for Flurl? Thanks!

**Comment by kinetiq** [comment]
Yes, eagerly awaiting this. :)

**Comment by Workshop2** [comment]
Hi all, progress is still happening (see SlackConnector for more info).

Flurl is done, but porting to a dot net core websocket client has been more work than expected. It is forcing me to address pings & connection health. I am working on this on my trains between home and work, however I have recently started a new job so progress is slower than I'd like.

Happy to see such interest :+1:

**Comment by Workshop2** [comment]
https://github.com/noobot/SlackConnector/issues/42

**Comment by jhayotte** [comment]
Hi @Workshop2,
Great news! I close my issue .
Good work :)

**Comment by Workshop2** [comment]
#95
