### ISSUE TITLE
How to use within a channel?

### ISSUE THREAD

**Issue by sophiaaar** [noobot/noobot#87]
Hello,

I added noobot to a Slack channel, and tried to use the commands within the channel, but it didn't work. I tried @noobot [command] too

How do I run noobot's commands while it is in a Slack channel?

**Comment by sophiaaar** [comment]
figured it out! @noobot does work

**Comment by Workshop2** [comment]
Hey, glad to hear it. You might need to invite @noobot into the channel with you
