### ISSUE TITLE
Noobot.Runner missing config.json from Configuration folder causes Noobot.Tests.Unit build failure. Bad initial experience w/ the project.

### ISSUE THREAD

**Issue by Coderrob** [noobot/noobot#90]
The `config.json` file is missing and causes the `Noobot.Tests.Unit` to fail during builds. The file is referenced from the project, but not included in source control. The README.md indicates there is an example in the Release zip. I pulled it down and it contained a `config.json` with the exact same settings format as the `config.default.json` contained in the Configuration folder. 

Line 172~
https://github.com/noobot/noobot/blob/master/src/Noobot.Runner/Noobot.Runner.csproj

Line 194~
https://github.com/noobot/noobot/blob/master/src/Noobot.Tests.Unit/Noobot.Tests.Unit.csproj

The `Noobot.Tests.Unit` is set to reference the `config.json` file. Should it not be updated to reference the `config.default.json`? The moment a fresh git clone build failed I would normally just remove the source and move on to another project.

**Comment by Workshop2** [comment]
This file is purposely ignored so I (or anyone else) doesn't check in slack keys into github. The idea is you just manually create a copy from default and don't have to worry about making it public.
