### ISSUE TITLE
Change handler mapping of build in middleware

### ISSUE THREAD

**Issue by liqdfire** [noobot/noobot#97]
How do I go about changing the handler mapping for the built in middleware.

I want to use the bot in a professional setting and would like to change the exact match handler for the help middle ware from "yo tell me more" to "tell me more"

**Comment by Workshop2** [comment]
I am happy to remove that mapping as I doubt it has been used. If you want to change it you can add your own help middleware and disable the standard help in the configuration

**Comment by Workshop2** [comment]
Released in 3.1.40
